version: '3.5'
services:
  postgresql:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    restart: always
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
    driver: local
